{% set name = "pybtex-docutils" %}
{% set version = "0.2.2" %}
{% set hash_type = "sha256" %}
{% set hash_value = "ea90935da188a0f4de2fe6b32930e185c33a0e306154322ccc12e519ebb5fa7d" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - setuptools
    - docutils >=0.8
    - pybtex >=0.16
    - six

test:
  commands:
    - python -c "import pybtex.plugin; pybtex.plugin.find_plugin('pybtex.backends', 'docutils')()"

about:
  home: https://github.com/mcmtroffaes/pybtex-docutils
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: A docutils backend for pybtex.
  description: A docutils backend for pybtex.
  doc_url: http://pybtex-docutils.readthedocs.org/
  dev_url: https://github.com/mcmtroffaes/pybtex-docutils

extra:
  recipe-maintainers:
    - croth1
