{% set name = "pybtex-docutils" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cead6554b4af99c287dd29f38b1fa152c9542f56a51cb6cbc3997c95b2725b2e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - setuptools
    - docutils >=0.8
    - pybtex >=0.16

test:
  commands:
    - python -c "import pybtex.plugin; pybtex.plugin.find_plugin('pybtex.backends', 'docutils')()"

about:
  home: https://github.com/mcmtroffaes/pybtex-docutils
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: A docutils backend for pybtex.
  description: A docutils backend for pybtex.
  doc_url: http://pybtex-docutils.readthedocs.org/
  dev_url: https://github.com/mcmtroffaes/pybtex-docutils

extra:
  recipe-maintainers:
    - croth1
